import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import { Poppins } from "next/font/google";
import { Theme } from "@radix-ui/themes";
const inter = Poppins({ weight: "400", subsets: ["latin"] });
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Theme>
        <body className={inter.className}>{children}</body>
      </Theme>
    </html>
  );
}
